rubric:
  possibleScore:
  - requirement: correct implementation of required functionality
    points: 50
  - requirement: code quality (how easy is your solution to follow)
    points: 5
  - requirement: quality of question answers in the questions.md file
    points: 10
  possibleExtraCredotScore:
  - requirement: implement an rc builtin command that contains the last command's return code
    points: 10
  requirements:
  - description: implement the cd internal command
    criteria:
    - cd command is implemented directly in code
    - with no arguments does nothing
    - with 1 argument changes directory of the current process to the argument
  - description: implement other commands with fork/exec
    criteria:
    - other than exit and cd, other commands should be implemented with fork/exec
    - multiple commands are NOT supported in this assignment, students do not need to handle <, >, and |
  - description: optional extra credit to implement rc command
    criteria:
    - rc command must return the exit code of the last command executed with fork/exec
  - description: answer the questions in questions.md
    criteria:
    - must place each quesiton answer after the question in questions.md
    - must provide a complete, correct, and thorough answer

